// File: Jurusan.js
// Auto-generated by SIAKAD CRUD Generator
// Generated at: 2026-07-22T16:45:49.250Z

/**
 * Ambil seluruh data jurusan dari sheet
 */
function getJurusan() {
  var sheet = getSheet("Jurusan");
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length > 0) data.shift();
  return data;
}

/**
 * Tambah data jurusan baru
 */
function createJurusan(obj) {
  try {
    if (!obj || !String(obj.nama || "").trim()) {
      return { success: false, message: "Nama jurusan tidak boleh kosong." };
    }
    var sheet = ensureSheet("Jurusan", ['ID', 'Nama', 'Kode']);
    var id = generateId("JUR");
    sheet.appendRow([id, String(obj.nama || "").trim(), String(obj.kode || "").trim()]);
    return { success: true, message: "Data Jurusan berhasil ditambahkan!" };
  } catch (error) {
    return { success: false, message: "Gagal menambah jurusan: " + error.message };
  }
}

/**
 * Update data jurusan
 */
function updateJurusan(obj) {
  try {
    if (!obj || !String(obj.id || "").trim()) {
      return { success: false, message: "ID jurusan tidak valid." };
    }
    var sheet = ensureSheet("Jurusan", ['ID', 'Nama', 'Kode']);
    var data = sheet.getDataRange().getValues();
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][0] || "").toString() === String(obj.id || "").toString()) {
        var rowIndex = i + 1;
        sheet.getRange(rowIndex, 2).setValue(String(obj.nama || "").trim());
        sheet.getRange(rowIndex, 3).setValue(String(obj.kode || "").trim());
        return { success: true, message: "Data Jurusan berhasil diperbarui!" };
      }
    }
    return { success: false, message: "Jurusan tidak ditemukan." };
  } catch (error) {
    return { success: false, message: "Gagal memperbarui jurusan: " + error.message };
  }
}

/**
 * Hapus data jurusan
 */
function deleteJurusan(id) {
  try {
    var sheet = ensureSheet("Jurusan", ['ID', 'Nama', 'Kode']);
    var data = sheet.getDataRange().getValues();
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][0] || "").toString() === String(id || "").toString()) {
        sheet.deleteRow(i + 1);
        return { success: true, message: "Data Jurusan berhasil dihapus!" };
      }
    }
    return { success: false, message: "Jurusan tidak ditemukan." };
  } catch (error) {
    return { success: false, message: "Gagal menghapus jurusan: " + error.message };
  }
}
/**
 * Helper untuk mengambil opsi nama mapel (digunakan di dropdown Form Guru)
 */
function getOptionsJurusan() {
  var sheet = getSheet('Jurusan');                  // Baca sheet "Mapel"
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length > 0) data.shift();              // Hapus baris header
  return data.map(function(r) {
    return { id: r[0], nama: r[1], kode: r[2] }; // Return array objek
  });
}