// File: Pembimbing.js
// Auto-generated by SIAKAD CRUD Generator
// Generated at: 2026-07-22T17:31:50.901Z

/**
 * Ambil seluruh data pembimbing dari sheet
 */
function getPembimbing() {
  var sheet = getSheet("Pembimbing");
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length > 0) data.shift();
  return data;
}

/**
 * Tambah data pembimbing baru
 */
function createPembimbing(obj) {
  try {
    if (!obj || !String(obj.nama || "").trim()) {
      return { success: false, message: "Nama pembimbing tidak boleh kosong." };
    }
    var sheet = ensureSheet("Pembimbing", ['ID', 'Nama', 'Kode']);
    var id = generateId("PUR");
    sheet.appendRow([id, String(obj.nama || "").trim(), String(obj.kode || "").trim()]);
    return { success: true, message: "Data Pembimbing berhasil ditambahkan!" };
  } catch (error) {
    return { success: false, message: "Gagal menambah pembimbing: " + error.message };
  }
}

/**
 * Update data pembimbing
 */
function updatePembimbing(obj) {
  try {
    if (!obj || !String(obj.id || "").trim()) {
      return { success: false, message: "ID pembimbing tidak valid." };
    }
    var sheet = ensureSheet("Pembimbing", ['ID', 'Nama', 'Kode']);
    var data = sheet.getDataRange().getValues();
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][0] || "").toString() === String(obj.id || "").toString()) {
        var rowIndex = i + 1;
        sheet.getRange(rowIndex, 2).setValue(String(obj.nama || "").trim());
        sheet.getRange(rowIndex, 3).setValue(String(obj.kode || "").trim());
        return { success: true, message: "Data Pembimbing berhasil diperbarui!" };
      }
    }
    return { success: false, message: "Pembimbing tidak ditemukan." };
  } catch (error) {
    return { success: false, message: "Gagal memperbarui pembimbing: " + error.message };
  }
}

/**
 * Hapus data pembimbing
 */
function deletePembimbing(id) {
  try {
    var sheet = ensureSheet("Pembimbing", ['ID', 'Nama', 'Kode']);
    var data = sheet.getDataRange().getValues();
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][0] || "").toString() === String(id || "").toString()) {
        sheet.deleteRow(i + 1);
        return { success: true, message: "Data Pembimbing berhasil dihapus!" };
      }
    }
    return { success: false, message: "Pembimbing tidak ditemukan." };
  } catch (error) {
    return { success: false, message: "Gagal menghapus pembimbing: " + error.message };
  }
}
function getOptionsPembimbing() {
  var sheet = getSheet('Pembimbing');                  // Baca sheet "Mapel"
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length > 0) data.shift();              // Hapus baris header
  return data.map(function(r) {
    return { id: r[0], nama: r[1], kode: r[2] }; // Return array objek
  });
}