// File: Projek.js
// Auto-generated by SIAKAD CRUD Generator
// Generated at: 2026-07-23T10:06:20.128Z

/**
 * Ambil seluruh data projek dari sheet
 */
function getProjek() {
  var sheet = getSheet("Projek");
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length > 0) data.shift();
  return data;
}

/**
 * Tambah data projek baru
 */
function createProjek(obj) {
  try {
    if (!obj || !String(obj.nama || "").trim()) {
      return { success: false, message: "Nama projek tidak boleh kosong." };
    }
    var sheet = ensureSheet("Projek", ['ID', 'Nama', 'Kode']);
    var id = generateId("PUR");
    sheet.appendRow([id, String(obj.nama || "").trim(), String(obj.kode || "").trim()]);
    return { success: true, message: "Data Projek berhasil ditambahkan!" };
  } catch (error) {
    return { success: false, message: "Gagal menambah projek: " + error.message };
  }
}

/**
 * Update data projek
 */
function updateProjek(obj) {
  try {
    if (!obj || !String(obj.id || "").trim()) {
      return { success: false, message: "ID projek tidak valid." };
    }
    var sheet = ensureSheet("Projek", ['ID', 'Nama', 'Kode']);
    var data = sheet.getDataRange().getValues();
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][0] || "").toString() === String(obj.id || "").toString()) {
        var rowIndex = i + 1;
        sheet.getRange(rowIndex, 2).setValue(String(obj.nama || "").trim());
        sheet.getRange(rowIndex, 3).setValue(String(obj.kode || "").trim());
        return { success: true, message: "Data Projek berhasil diperbarui!" };
      }
    }
    return { success: false, message: "Projek tidak ditemukan." };
  } catch (error) {
    return { success: false, message: "Gagal memperbarui projek: " + error.message };
  }
}

/**
 * Hapus data projek
 */
function deleteProjek(id) {
  try {
    var sheet = ensureSheet("Projek", ['ID', 'Nama', 'Kode']);
    var data = sheet.getDataRange().getValues();
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][0] || "").toString() === String(id || "").toString()) {
        sheet.deleteRow(i + 1);
        return { success: true, message: "Data Projek berhasil dihapus!" };
      }
    }
    return { success: false, message: "Projek tidak ditemukan." };
  } catch (error) {
    return { success: false, message: "Gagal menghapus projek: " + error.message };
  }
}

/**
 * Helper untuk mengambil opsi projek (digunakan di dropdown Form Tugas)
 */
function getOptionsProjek() {
  var sheet = getSheet('Projek');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length > 0) data.shift();
  return data.map(function(r) {
    return { id: r[0], nama: r[1], kode: r[2] };
  });
}

