// File: Sekolah.js
// Auto-generated by SIAKAD CRUD Generator
// Generated at: 2026-07-23T10:06:20.128Z

/**
 * Ambil seluruh data sekolah dari sheet
 */
function getSekolah() {
  var sheet = getSheet("Sekolah");
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length > 0) data.shift();
  return data;
}

/**
 * Tambah data sekolah baru
 */
function createSekolah(obj) {
  try {
    if (!obj || !String(obj.nama || "").trim()) {
      return { success: false, message: "Nama sekolah tidak boleh kosong." };
    }
    var sheet = ensureSheet("Sekolah", ['ID', 'Nama', 'Kode']);
    var id = generateId("SUR");
    sheet.appendRow([id, String(obj.nama || "").trim(), String(obj.kode || "").trim()]);
    return { success: true, message: "Data Sekolah berhasil ditambahkan!" };
  } catch (error) {
    return { success: false, message: "Gagal menambah sekolah: " + error.message };
  }
}

/**
 * Update data sekolah
 */
function updateSekolah(obj) {
  try {
    if (!obj || !String(obj.id || "").trim()) {
      return { success: false, message: "ID sekolah tidak valid." };
    }
    var sheet = ensureSheet("Sekolah", ['ID', 'Nama', 'Kode']);
    var data = sheet.getDataRange().getValues();
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][0] || "").toString() === String(obj.id || "").toString()) {
        var rowIndex = i + 1;
        sheet.getRange(rowIndex, 2).setValue(String(obj.nama || "").trim());
        sheet.getRange(rowIndex, 3).setValue(String(obj.kode || "").trim());
        return { success: true, message: "Data Sekolah berhasil diperbarui!" };
      }
    }
    return { success: false, message: "Sekolah tidak ditemukan." };
  } catch (error) {
    return { success: false, message: "Gagal memperbarui sekolah: " + error.message };
  }
}

/**
 * Hapus data sekolah
 */
function deleteSekolah(id) {
  try {
    var sheet = ensureSheet("Sekolah", ['ID', 'Nama', 'Kode']);
    var data = sheet.getDataRange().getValues();
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][0] || "").toString() === String(id || "").toString()) {
        sheet.deleteRow(i + 1);
        return { success: true, message: "Data Sekolah berhasil dihapus!" };
      }
    }
    return { success: false, message: "Sekolah tidak ditemukan." };
  } catch (error) {
    return { success: false, message: "Gagal menghapus sekolah: " + error.message };
  }
}
function getOptionsSekolah() {
  var sheet = getSheet('Sekolah');                  // Baca sheet "Mapel"
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length > 0) data.shift();              // Hapus baris header
  return data.map(function(r) {
    return { id: r[0], nama: r[1], kode: r[2] }; // Return array objek
  });
}