// File: Siswa.js
// Auto-generated by SIAKAD CRUD Generator
// Generated at: 2026-07-22T15:50:39.278Z

/**
 * Ambil seluruh data siswa dari sheet
 */
function getSiswa() {
  var sheet = getSheet("Siswa");
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length > 0) data.shift();
  return sanitizeData(data);
}

/**
 * Tambah data siswa baru
 */
function createSiswa(obj) {
  try {
    if (!obj || !String(obj.nama || "").trim()) {
      return { success: false, message: "Nama siswa tidak boleh kosong." };
    }
    var sheet = ensureSheet("Siswa", ['ID', 'Nama', 'Kelas', 'Jurusan', 'Sekolah', 'PeriodeAwal', 'PeriodeAkhir', 'Pembimbing', 'Surat', 'TanggalSurat']);
    var id = generateId("SUR");
    sheet.appendRow([id, String(obj.nama || "").trim(), String(obj.kelas || "").trim(), String(obj.Jurusan || "").trim(), String(obj.Sekolah || "").trim(), String(obj.PeriodeAwal || "").trim(), String(obj.PeriodeAkhir || "").trim(), String(obj.Pembimbing || "").trim(), String(obj.Surat || "").trim(), String(obj.TanggalSurat || "").trim()]);
    return { success: true, message: "Data Siswa berhasil ditambahkan!" };
  } catch (error) {
    return { success: false, message: "Gagal menambah siswa: " + error.message };
  }
}

/**
 * Update data siswa
 */
function updateSiswa(obj) {
  try {
    if (!obj || !String(obj.id || "").trim()) {
      return { success: false, message: "ID siswa tidak valid." };
    }
    var sheet = ensureSheet("Siswa", ['ID', 'Nama', 'Kelas', 'Jurusan', 'Sekolah', 'PeriodeAwal', 'PeriodeAkhir', 'Pembimbing', 'Surat', 'TanggalSurat']);
    var data = sheet.getDataRange().getValues();
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][0] || "").toString() === String(obj.id || "").toString()) {
        var rowIndex = i + 1;
        sheet.getRange(rowIndex, 2).setValue(String(obj.nama || "").trim());
        sheet.getRange(rowIndex, 3).setValue(String(obj.kelas || "").trim());
        sheet.getRange(rowIndex, 4).setValue(String(obj.Jurusan || "").trim());
        sheet.getRange(rowIndex, 5).setValue(String(obj.Sekolah || "").trim());
        sheet.getRange(rowIndex, 6).setValue(String(obj.PeriodeAwal || "").trim());
        sheet.getRange(rowIndex, 7).setValue(String(obj.PeriodeAkhir || "").trim());
        sheet.getRange(rowIndex, 8).setValue(String(obj.Pembimbing || "").trim());
        sheet.getRange(rowIndex, 9).setValue(String(obj.Surat || "").trim());
        sheet.getRange(rowIndex, 10).setValue(String(obj.TanggalSurat || "").trim());
        return { success: true, message: "Data Siswa berhasil diperbarui!" };
      }
    }
    return { success: false, message: "Siswa tidak ditemukan." };
  } catch (error) {
    return { success: false, message: "Gagal memperbarui siswa: " + error.message };
  }
}

/**
 * Hapus data siswa
 */
function deleteSiswa(id) {
  try {
    var sheet = ensureSheet("Siswa", ['ID', 'Nama', 'Kelas', 'Jurusan', 'Sekolah', 'PeriodeAwal', 'PeriodeAkhir', 'Pembimbing', 'Surat', 'TanggalSurat']);
    var data = sheet.getDataRange().getValues();
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][0] || "").toString() === String(id || "").toString()) {
        sheet.deleteRow(i + 1);
        return { success: true, message: "Data Siswa berhasil dihapus!" };
      }
    }
    return { success: false, message: "Siswa tidak ditemukan." };
  } catch (error) {
    return { success: false, message: "Gagal menghapus siswa: " + error.message };
  }
}


